//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRoutingSlip
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedListSignature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LinkedListSignature()
        {
            this.LinkedListSignatureNodes = new HashSet<LinkedListSignatureNode>();
            this.RoutingSlips = new HashSet<RoutingSlip>();
        }
    
        public int ID { get; set; }
        public int RoutingSlipID { get; set; }
        public string CurrentName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkedListSignatureNode> LinkedListSignatureNodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutingSlip> RoutingSlips { get; set; }
    }
}
