//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRoutingSlip
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedListSignatureNode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LinkedListSignatureNode()
        {
            this.LinkedListSignatureNodes1 = new HashSet<LinkedListSignatureNode>();
            this.LinkedListSignatureNodes11 = new HashSet<LinkedListSignatureNode>();
        }
    
        public int ID { get; set; }
        public int RoutingSlipID { get; set; }
        public Nullable<int> Data_SignatureID { get; set; }
        public Nullable<int> NextSNode_ID { get; set; }
        public Nullable<int> PrevSNode_ID { get; set; }
        public Nullable<int> LinkedListSignature_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkedListSignatureNode> LinkedListSignatureNodes1 { get; set; }
        public virtual LinkedListSignatureNode LinkedListSignatureNode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkedListSignatureNode> LinkedListSignatureNodes11 { get; set; }
        public virtual LinkedListSignatureNode LinkedListSignatureNode2 { get; set; }
        public virtual LinkedListSignature LinkedListSignature { get; set; }
        public virtual Signature Signature { get; set; }
    }
}
