//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRoutingSlip
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutingSlip
    {
        public int RoutingSlipID { get; set; }
        public string DocumentName { get; set; }
        public string RequestingEmployee { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public string ForwardTo { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<int> LinkedListSignature_ID { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual LinkedListSignature LinkedListSignature { get; set; }
    }
}
