// <auto-generated />
namespace eRoutingSlip.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PrevNode_ID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrevNode_ID));
        
        string IMigrationMetadata.Id
        {
            get { return "201805032243218_PrevNode_ID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
